on:
  push:
    branches:
      - master
      - ga-test

name: Compile and Update Latest Release

jobs:
  build:
    name: Run MSBuild
    runs-on: windows-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v3.0.0
      id: checkout_code

    - name: Setup MSBuild and add to PATH
      uses: microsoft/setup-msbuild@v1.1
      with:
        msbuild-architecture: x86
      id: setup_msbuild

    - name: Run MSBuild
      id: run_msbuild
      run: msbuild .\OwnaClicker.sln -property:Configuration=Release 