name: "Build"

on:
  push:
    branches:
      - master
      - ga-test
    
jobs:
  run-msbuild-vstest:
  runs-on: windows-latest
  name: Run MSBuild
  
  steps:
    - name: Checkout code
      uses: actions/checkout@v2.1.0
      id: checkout_code

    - name: Setup MSBuild and add to PATH
      uses: microsoft/setup-msbuild@v1.0.0
      id: setup_msbuild

    - name: Run MSBuild
      id: run_msbuild
      working-directory: $
      run: msbuild .\OwnaClicker.sln